config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :my_threads do
    scope module: :my_threads do
      resources :comments
    end
  end
  root to: "my_threads#index"
  devise_for :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :my_thread
  belongs_to :user
end

app/models/my_thread.rb
class MyThread < ApplicationRecord
  has_many :comments
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :my_threads
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
before_action :authenticate_user!
end

app/controllers/my_threads/comments_controller.rb
class MyThreads::CommentsController < ApplicationController
  before_action :set_my_thread 
  before_action :set_comment_admin, only: [:edit, :update, :destroy]

  def index
    @comments=Comment.where(my_thread_id:params[:my_thread_id])
    @current_user_id=current_user.id
  end

  def new
    @comment=@my_thread.comments.new
  end

  def create
    @my_thread.comments.create(comment_params.merge(user_id: current_user.id))
    redirect_to my_thread_comments_path(@my_thread)
  end

  def edit
  end

  def update
    @comment.update(comment_params)
    redirect_to my_thread_comments_path(my_thread_id: @my_thread)
  end

  def destroy
    @comment.destroy
    redirect_to my_thread_comments_path(my_thread_id: @my_thread)
  end

  private
  def set_my_thread
    @my_thread=MyThread.find(params[:my_thread_id])
  end

  def set_comment_admin
    @comment=Comment.find_by!(id: params[:id], user_id: current_user.id)
  end

  def comment_params
    params.require(:comment).permit(:body)
  end
end

app/controllers/my_threads_controller.rb
class MyThreadsController < ApplicationController
  before_action :set_my_thread_admin, only: [:edit, :update, :destroy]
  before_action :set_current_user_id, only: [:index, :show]

  def index
    @my_threads=MyThread.all
  end

  def create
    MyThread.create(my_thread_params.merge(user_id: current_user.id))
    redirect_to my_threads_path
  end

  def new
    @my_thread=MyThread.new
  end

  def edit
  end

  def show
    @my_thread=MyThread.find(params[:id])
  end

  def update
    @my_thread.update(my_thread_params)
    redirect_to @my_thread
  end

  def destroy
    @my_thread.destroy
    redirect_to my_threads_path
  end

  private
  def set_my_thread_admin
    @my_thread=MyThread.find_by!(id:params[:id], user_id:current_user.id)
  end

  def set_current_user_id
    @current_user_id=current_user.id
  end

  def my_thread_params
    params.require(:my_thread).permit(:title)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/my_threads/comments_helper.rb
module MyThreads::CommentsHelper
end

app/helpers/my_threads_helper.rb
module MyThreadsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BoardPlus</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if user_signed_in? %>
      ログイン中: <strong><%= current_user.email %></strong>
    <%= link_to 'プロフィール変更', edit_user_registration_path %> |
    <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
  <% else %>
    <%= link_to "サインアップ", new_user_registration_path %> |
    <%= link_to "ログイン", new_user_session_path %>
  <% end %>
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/my_threads/_form.html.erb
<%= form_with(model: my_thread, local: true) do |form| %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/my_threads/comments/_form.html.erb
<%= form_with(model: [my_thread,comment], local: true) do |form| %>
    <%= form.text_field :body %>
      <%= form.submit %>
<% end %>

app/views/my_threads/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render partial: 'form', locals: {my_thread: @my_thread,  comment: @comment} %>

<%= link_to 'Back', my_thread_comments_path(@my_thread) %>

app/views/my_threads/comments/index.html.erb
<h1>Comments</h1>

<table>
  <thead>
    <tr>
      <th>Comments</th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.body %></td>
        <% if comment.user_id==@current_user_id %>
        <td><%= link_to 'Edit', edit_my_thread_comment_path(my_thread_id: @my_thread, id: comment) %></td>
        <td><%= link_to 'Destroy', my_thread_comment_path(my_thread_id: @my_thread, id: comment), method: :delete %></td>
      <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_my_thread_comment_path(my_thread_id: @my_thread) %>
<%= link_to 'Back', my_thread_path(@my_thread) %>

app/views/my_threads/comments/new.html.erb
<h1>New Comment</h1>

<%= render partial: 'form', locals: {my_thread: @my_thread,  comment: @comment} %>

<%= link_to 'Back', my_thread_comments_path(my_thread_id: @my_thread) %>

app/views/my_threads/edit.html.erb
<h1>Editing My Thread</h1>

<%= render 'form', my_thread: @my_thread %>

<%= link_to 'Show', @my_thread %> 
<%= link_to 'Back', my_threads_path %>

app/views/my_threads/index.html.erb
<h1>My Threads</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
    </tr>
  </thead>

  <tbody>
    <% @my_threads.each do |my_thread| %>
      <tr>
        <td><%= my_thread.title %></td>
        <td><%= link_to 'Show', my_thread %></td>
        <% if my_thread.user_id == @current_user_id then %>
        <td><%= link_to 'Edit', edit_my_thread_path(my_thread) %></td>
        <td><%= link_to 'Destroy', my_thread, method: :delete %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New My Thread', new_my_thread_path %>

app/views/my_threads/new.html.erb
<h1>New My Thread</h1>

<%= render partial: 'form', locals: {my_thread: @my_thread} %>

<%= link_to 'Back', my_threads_path %>

app/views/my_threads/show.html.erb
<p>
  Title:  <%= @my_thread.title %>
</p>

<%= link_to "Show Comment", my_thread_comments_path(my_thread_id: @my_thread) %>

<% if @my_thread.user_id==@current_user_id %>
<%= link_to 'Edit', edit_my_thread_path(my_thread_id: @my_thread) %> 
<% end %>
<%= link_to 'Back', my_threads_path %>